name: XXXX
description: Potatoing around town
meta_description: "Your New Jekyll Site, Blogging about stuffs"

markdown: kramdown
highlighter: rouge
logo: false
paginate: 15
baseurl: /
domain_name: 'http://yourblog-domain.com'
google_analytics: 'UA-XXXXXXXX-X'
gems: [jekyll-paginate]
tag_page: '/tags'
category_page: '/categories'

# Details for the RSS feed generator
url:            'blog url'
author:         'Jun'
